name: Build Every 4 Hours

on:
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Call the build API
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
        --header 'authorization: Bearer ${{ secrets.DEPLOY_PAT }}' \
        --header 'content-type: application/json'
